[package]
name = "conecta2"
version = "0.1.0"
authors = ["raytrapi <sdfenix@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono="0.4"
base64="0.3.1"
sha-1="0.8.1"